name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --frozen-lockfile

      # Pass API URL to the build process
      - name: Build
        run: yarn build
        env:
          VITE_PUBLIC_API_URL: ${{ secrets.API_URL }}

      # Enable use of custom domain
      - name: Configure custom domain
        run: echo "feikegeerts.nl" > build/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: feikegeerts.nl
